'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _1_up() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_up", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockBrick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockBrick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockGround() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockGround", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockGround1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockGround1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockInvis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockInvis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockMetal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockMetal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockQuestion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockQuestion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockQuestion2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockQuestion2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockQuestion3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockQuestion3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockQuestionUsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockQuestionUsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property brick_smash() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_smash", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloud_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloud_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloud_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloud_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_hit_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_hit_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_hit_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_hit_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_hit_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_hit_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_hit_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_hit_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_idle_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_idle_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_idle_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_idle_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin_idle_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_idle_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property coin_pickup() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_pickup", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f_flower_s7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f_flower_s7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireball_expl_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireball_expl_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireball_expl_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireball_expl_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireball_expl_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireball_expl_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flagpole_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flagpole_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flagpole_head() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flagpole_head", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flagpole_stem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flagpole_stem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goomba_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goomba_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goomba_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goomba_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goomba_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goomba_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goomba_d2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goomba_d2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ground_theme() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ground_theme", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hill_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hill_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hill_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hill_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HUDitemBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HUDitemBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property jump() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("jump", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_1r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_1r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_2r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_2r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_shell1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_shell1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_shell2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_shell2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_green_shellr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_green_shellr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_greenf_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_greenf_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property koopa_greenf_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koopa_greenf_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property map1_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("map1_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_1r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_1r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_2r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_2r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_3r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_3r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_4r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_4r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_climb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_climb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_crouch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_crouch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_crouchr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_crouchr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_jump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_jump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_big_jumpr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_big_jumpr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_1r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_1r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_2r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_2r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_3r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_3r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_4r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_4r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_climb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_climb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_crouch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_crouch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_crouchr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_crouchr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_jump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_jump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_bigf_jumpr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_bigf_jumpr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_1r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_1r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_2r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_2r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_3r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_3r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_4r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_4r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_climb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_climb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_dead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_dead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_jump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_jump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario_small_jumpr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario_small_jumpr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mushroom_pickup() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_pickup", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_s7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_s7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NES() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NES", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pipe_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipe_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pipe_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipe_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property player_dead() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("player_dead", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_s7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_s7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SuperMario256() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMario256", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property warp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("warp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
